DROP TABLE "Specialista" CASCADE CONSTRAINTS;
DROP TABLE "Zakaznik" CASCADE CONSTRAINTS;
DROP TABLE "Oprava" CASCADE CONSTRAINTS;
DROP TABLE "Vozidlo" CASCADE CONSTRAINTS;
DROP TABLE "Material" CASCADE CONSTRAINTS;
DROP TABLE "Faktura" CASCADE CONSTRAINTS;
DROP TABLE "Vykonava_cinnost" CASCADE CONSTRAINTS;
DROP TABLE "Automechanik" CASCADE CONSTRAINTS;